version: '3'


x-base-image: &base-image
  restart: always
  env_file:
      - .env


services:
  postgres:
    <<: *base-image
    image: 'postgres:15-alpine'
    hostname: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    <<: *base-image
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    volumes:
      - ./src:/edu/src
    command: python3 src/app/main.py
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  minio:
    <<: *base-image
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server --console-address :9090 /data
    volumes:
      - ./minio/data:/data
      - ./minio/conf:/root/.minio